### ISSUE TITLE
vcruntime140d.dll and ucrtbased.dll required

### ISSUE THREAD

**Issue by Kinny092** [itm4n/Perfusion#1]
Hi,

The dlls in the subject are missing and Perfusion could not run. I tried to googled and found out that I will have to install Visual C++ 2015 x64 14.0.24123, I decided not to remove my current packages as that might nuke other software so I went to the following websites to download the DLL files and save it to the same Debug directory.
https://www.dll-files.com/vcruntime140d.dll.html
https://www.dll-files.com/ucrtbased.dll.html

There are quite a lot of versions so I downloaded the following x64 files
vcruntime140d.dll - SHA1 - 4021b804469816c3136b40c4ceb44c8d60ed15f5
ucrtbased.dll - SHA1 - 56c2e8fb1af609525b0f732bb67b806bddab3752

Tried a second time with: 
vcruntime140d.dll - SHA1 - bcbc1ebd5a592c2df216d3211f309a79f9cd8a9b

Checked my Windows 10 and I have the following installed.
![image](https://user-images.githubusercontent.com/25901267/116396350-7058dd00-a864-11eb-9903-66b84ed6e816.png)
Running as Administrator CMD, I got the following error 1813 
![image](https://user-images.githubusercontent.com/25901267/116396630-c3329480-a864-11eb-9330-0d90a01c4b8d.png)
![image](https://user-images.githubusercontent.com/25901267/116396692-d6456480-a864-11eb-8cc3-9f6c161e6e89.png)

Checked my Windows Server 2012 and I have the following installed.
![image](https://user-images.githubusercontent.com/25901267/116397363-a9458180-a865-11eb-81b3-77cad453a391.png)
![image](https://user-images.githubusercontent.com/25901267/116397303-99c63880-a865-11eb-8aca-61e06a2806b2.png)
![image](https://user-images.githubusercontent.com/25901267/116397450-c1b59c00-a865-11eb-8e78-2fad4e3913cc.png)

Tried to use the 32 bit files on 2012 and perfusion would not even run.
![image](https://user-images.githubusercontent.com/25901267/116398027-764fbd80-a866-11eb-8bca-faf1ba3ed33d.png)
vcruntime140d.dll - SHA1 - e1b692518cf0d4a67c63ed95c9655c002d79b0cd
vcruntime140d.dll - SHA1 - aa18ef3884a6ee4f9e352ed86b958a15d62ce711
vcruntime140d.dll - SHA1 - cd93187f3895dcc8ebb0efeb483eec15b848ef36
ucrtbased.dll - SHA1 - 9529cc4ee868a9f5cf996f7075e45b9619c066a6

**Comment by itm4n** [comment]
RTFM
